# render.yaml
services:
  - type: web
    name: pesaprime-backend
    env: python
    plan: free
    buildCommand: |
      python -m pip install --upgrade pip setuptools wheel
      pip install --use-pep517 --no-cache-dir -r requirements.txt
      
    startCommand: python -m uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        value: sqlite:///./PesaPrime.db
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 30